apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway-service
  namespace: distributed-system
spec:
  ports:
    - port: 80
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: distributed-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      hostname: gateway
      containers:
        - name: gateway
          image: timmijinks/ds-gateway
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "500Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
