apiVersion: v1
kind: Service
metadata:
  labels:
    app: image
  name: image-service
  namespace: distributed-system
spec:
  ports:
    - port: 80
  selector:
    app: image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: image
  name: image
  namespace: distributed-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      hostname: image
      containers:
        - name: image
          image: timmijinks/ds-image
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "500Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
